#!/bin/bash
mkdir -p "app/(auth)/login"
mkdir -p "app/(auth)/register"
mkdir -p "app/(dashboard)/dashboard"
mkdir -p "app/(dashboard)/browse"
mkdir -p "app/(dashboard)/messages"
mkdir -p "app/(dashboard)/profile"
mkdir -p "app/(dashboard)/wallet"
mkdir -p "app/(admin)/admin"
mkdir -p "app/api/clerk-webhook"
mkdir -p "app/api/pesapal-callback"
mkdir -p "app/api/pesapal-ipn"
mkdir -p "app/blog"
mkdir -p "app/blog/[slug]"
mkdir -p "components/ui"
mkdir -p "components/auth"
mkdir -p "components/dashboard"
mkdir -p "components/browse"
mkdir -p "components/messages"
mkdir -p "components/wallet"
mkdir -p "components/admin"
mkdir -p "components/blog"
mkdir -p "lib/supabase"
mkdir -p "lib/clerk"
mkdir -p "lib/pesapal"
mkdir -p "types"
mkdir -p "hooks"
echo "Directory structure created"
